Repository SithCult/Holobook, pull requests merged in 2020-07, with the labels that each got.

#30 Add youtube aa1
  .vscode/settings.json
  package.json
  src/components/molecules/Post/index.jsx
  src/components/organisms/Posts/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
Labels: enhancement

#31 Unregister registerServiceWorker
  package.json
  src/index.js
Labels: enhancement

#32 Fix posting aa1
  package.json
  src/components/pages/ProfilePage/index.jsx
  src/index.js
  src/registerServiceWorker.js
Labels: bug

#35 Add online users aa1
  src/components/molecules/OnlineUsers/index.jsx
  src/components/molecules/index.js
  src/components/pages/ProfilePage/index.jsx
  src/store/actions/userActions.js
  src/store/reducers/likeReducer.js
  src/store/reducers/userReducer.js
Labels: enhancement

#36 Add online users aa1 to improve post aa1
  src/components/molecules/OnlineUsers/index.jsx
  src/components/organisms/Comments/comments.scss
  src/components/organisms/Comments/index.jsx
  src/components/pages/CountryPage/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
Labels: enhancement

#37 Improve countrypage aa1 to improve post aa1
  src/App.js
  src/components/pages/CountryPage/countrypage.scss
  src/components/pages/CountryPage/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/store/actions/userActions.js
Labels: enhancement

#38 Add online users ba1
  src/components/molecules/Comment/index.jsx
  src/components/molecules/CookieModal/index.jsx
  src/components/molecules/OnlineUsers/index.jsx
  src/components/molecules/OnlineUsers/onlineusers.scss
  src/components/molecules/Post/index.jsx
  src/components/organisms/Comments/index.jsx
  src/components/organisms/Posts/index.jsx
  src/components/organisms/RegisterForm/index.jsx
  src/components/pages/CountryPage/countrypage.scss
  src/components/pages/CountryPage/index.jsx
  src/components/pages/DonatePage/index.jsx
  src/components/pages/ImperialBasicTraining/index.jsx
  src/components/pages/LoginPage/index.jsx
  src/components/pages/MessagePage/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
  src/store/actions/authActions.js
  src/store/actions/commentActions.js
  src/store/actions/postActions.js
  src/store/actions/userActions.js
Labels: documentation, enhancement

#34 Improve post aa1 to master
  package.json
  src/App.js
  src/Routes.js
  src/components/molecules/Comment/index.jsx
  src/components/molecules/CookieModal/index.jsx
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/Navbar/navbar.scss
  src/components/molecules/OnlineUsers/index.jsx
  src/components/molecules/OnlineUsers/onlineusers.scss
  src/components/molecules/Post/index.jsx
  src/components/molecules/ReceivedUser/index.jsx
  src/components/molecules/ReceivedUser/receiveduser.scss
  src/components/molecules/index.js
  src/components/molecules/modals/AboutUs/index.jsx
  src/components/organisms/Comments/comments.scss
  src/components/organisms/Comments/index.jsx
  src/components/organisms/Posts/index.jsx
  src/components/organisms/Posts/posts.scss
  src/components/organisms/RegisterForm/index.jsx
  src/components/organisms/RegisterForm/registerform.scss
  src/components/pages/CountryPage/countrypage.scss
  src/components/pages/CountryPage/index.jsx
  src/components/pages/DonatePage/donate.scss
  src/components/pages/DonatePage/index.jsx
  src/components/pages/HomePage/index.jsx
  src/components/pages/ImperialBasicTraining/index.jsx
  src/components/pages/LoginPage/index.jsx
  src/components/pages/MessagePage/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
  src/components/pages/index.js
  src/store/actions/authActions.js
  src/store/actions/commentActions.js
  src/store/actions/postActions.js
  src/store/actions/userActions.js
  src/store/reducers/likeReducer.js
  src/store/reducers/userReducer.js
Labels: bug, enhancement

#39 Add online users ba1
  src/App.js
  src/components/molecules/Navbar/index.jsx
  src/components/pages/CountryPage/index.jsx
  src/components/pages/LoginPage/index.jsx
  src/store/actions/userActions.js
Labels: bug, enhancement

#43 Fix trainer
  package.json
  src/components/pages/ImperialBasicTraining/index.jsx
Labels: bug

#45 Fix presence system
  package.json
  src/store/actions/userActions.js
Labels: bug

#46 Fix presence ba1
  package.json
  src/assets/images/icons/holocron.png
  src/components/pages/ProfilePage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
  src/store/actions/userActions.js
Labels: bug

#47 Improve deployment
  package.json
Labels: enhancement

#48 Add chat components aa1 to add chat aa1
  package.json
  src/components/molecules/MessageItem/index.jsx
  src/components/molecules/MessageItem/messageitem.scss
  src/components/molecules/index.js
  src/components/organisms/Chat/chat.scss
  src/components/organisms/Chat/index.jsx
  src/components/organisms/index.js
  src/components/pages/CountryPage/index.jsx
Labels: enhancement

#50 Add chat aa1 to implement 1
  package.json
  src/Routes.js
  src/assets/images/bronze.gif
  src/assets/images/dark.gif
  src/assets/images/gold.gif
  src/assets/images/light.gif
  src/components/atoms/RankItem/index.jsx
  src/components/atoms/RankItem/rankitem.scss
  src/components/atoms/index.js
  src/components/molecules/MessageItem/index.jsx
  src/components/molecules/MessageItem/messageitem.scss
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/OnlineUsers/index.jsx
  src/components/molecules/ReceivedUser/index.jsx
  src/components/molecules/ReceivedUser/receiveduser.scss
  src/components/molecules/index.js
  src/components/organisms/Chat/chat.scss
  src/components/organisms/Chat/index.jsx
  src/components/organisms/index.js
  src/components/pages/ChatPage/chatpage.scss
  src/components/pages/ChatPage/index.jsx
  src/components/pages/CountryPage/countrypage.scss
  src/components/pages/CountryPage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
  src/components/pages/index.js
  src/store/actions/chatActions.js
  src/store/actions/userActions.js
  src/store/reducers/chatReducer.js
  src/store/reducers/rootReducer.js
Labels: enhancement

#52 Fix comment duplicates
  src/components/organisms/Comments/index.jsx
Labels: bug

#53 Add chat ba1
  src/components/molecules/MessageItem/index.jsx
  src/components/molecules/MessageItem/messageitem.scss
  src/components/molecules/OnlineUsers/index.jsx
  src/components/organisms/Chat/index.jsx
  src/components/pages/ChatPage/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/store/actions/chatActions.js
  src/store/reducers/commentReducer.js
  src/store/reducers/postReducer.js
Labels: enhancement

#54 Add chat ca1
  src/components/molecules/MessageItem/index.jsx
  src/components/molecules/MessageItem/messageitem.scss
  src/components/organisms/Chat/chat.scss
  src/components/organisms/Chat/index.jsx
  src/components/pages/ChatPage/index.jsx
  src/components/pages/CountryPage/index.jsx
  src/store/actions/chatActions.js
Labels: bug

#57 Fix join chat feature
  src/components/organisms/Chat/index.jsx
Labels: bug

#58 Add chat ea1
  src/assets/images/icons/holocron.png
  src/components/organisms/Chat/index.jsx
  src/components/organisms/RegisterForm/index.jsx
  src/components/pages/ChatPage/chatpage.scss
  src/components/pages/ChatPage/index.jsx
  src/components/pages/CountryPage/index.jsx
  src/store/actions/authActions.js
Labels: bug, enhancement

#59 Implement 1 to master
  package.json
  src/Routes.js
  src/assets/images/bronze.gif
  src/assets/images/dark.gif
  src/assets/images/gold.gif
  src/assets/images/icons/holocron.png
  src/assets/images/light.gif
  src/components/atoms/RankItem/index.jsx
  src/components/atoms/RankItem/rankitem.scss
  src/components/atoms/index.js
  src/components/molecules/MessageItem/index.jsx
  src/components/molecules/MessageItem/messageitem.scss
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/OnlineUsers/index.jsx
  src/components/molecules/ReceivedUser/index.jsx
  src/components/molecules/ReceivedUser/receiveduser.scss
  src/components/molecules/index.js
  src/components/organisms/Chat/chat.scss
  src/components/organisms/Chat/index.jsx
  src/components/organisms/Comments/index.jsx
  src/components/organisms/RegisterForm/index.jsx
  src/components/organisms/index.js
  src/components/pages/ChatPage/chatpage.scss
  src/components/pages/ChatPage/index.jsx
  src/components/pages/CountryPage/countrypage.scss
  src/components/pages/CountryPage/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
  src/components/pages/index.js
  src/store/actions/authActions.js
  src/store/actions/chatActions.js
  src/store/actions/userActions.js
  src/store/reducers/chatReducer.js
  src/store/reducers/commentReducer.js
  src/store/reducers/postReducer.js
  src/store/reducers/rootReducer.js
Labels: bug, enhancement

#60 Fix issue
  src/components/pages/ChatPage/index.jsx
Labels: bug

#61 Add notifications aa1 to master
  package.json
  src/App.js
  src/components/molecules/MessageItem/index.jsx
  src/components/molecules/MessageItem/messageitem.scss
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/Navbar/navbar.scss
  src/components/molecules/NotificationItem/index.jsx
  src/components/molecules/NotificationItem/notificationitem.scss
  src/components/molecules/index.js
  src/components/organisms/Chat/index.jsx
  src/components/organisms/NotifBox/index.jsx
  src/components/organisms/index.js
  src/components/pages/ChatPage/index.jsx
  src/store/actions/chatActions.js
  src/store/actions/notificationActions.js
  src/store/actions/userActions.js
  src/store/reducers/notificationReducer.js
  src/store/reducers/rootReducer.js
Labels: bug, enhancement

#66 Add push notifs aa1 to master
  package.json
  src/App.js
  src/components/molecules/MessageItem/index.jsx
  src/components/organisms/Chat/index.jsx
  src/components/pages/ChatPage/index.jsx
Labels: bug, enhancement

#67 Fix chat notification clicks to master
  package.json
  src/components/pages/ChatPage/index.jsx
Labels: bug

#68 Improve chat aa1 to master
  .env.template
  package.json
  src/App.js
  src/components/molecules/MessageItem/index.jsx
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/NotificationItem/index.jsx
  src/components/molecules/Post/index.jsx
  src/components/molecules/ReceivedUser/index.jsx
  src/components/organisms/Chat/chat.scss
  src/components/organisms/Chat/index.jsx
  src/components/organisms/Posts/posts.scss
  src/components/pages/ChatPage/chatpage.scss
  src/components/pages/ChatPage/index.jsx
  src/components/pages/CountryPage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
  src/store/actions/chatActions.js
  src/utilities/_base.scss
Labels: bug, enhancement

#69 Improve chat ba1 to master
  package.json
  src/components/molecules/NotificationItem/index.jsx
  src/components/molecules/ReceivedUser/index.jsx
  src/components/organisms/Chat/index.jsx
  src/components/pages/ChatPage/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/components/pages/ProfilePage/profilepage.scss
  src/store/actions/chatActions.js
  src/store/reducers/chatReducer.js
  src/utilities/_base.scss
Labels: bug, enhancement
